### ISSUE TITLE
Custom values

### ISSUE THREAD

**Issue by technobiker** [Imaginous/Cowboy_Untamed#25]
Hi!

How can we calculate the different values for iOS, such as 5%? I want to try out all values so I can get the perfect tune for my style.
I'd also like to set my speed limit to a different value such as 30 km/h. Is that also possible?

**Comment by Imaginous** [comment]
If you want to try out all values, use a cheap Android phone with the Untamed app.
You can generate the values in there and write down the different codes.

There is quite some code to determine the values and calculate the Base64 checksum.


Untamed doesn't change or set the speed limit.
The speed limit is either enabled or disabled.
I have seen instances where the speed limit is overwritten by the original app.
That's why I don't tinker with it.
