### ISSUE TITLE
why closed source?

### ISSUE THREAD

**Issue by thrillfall** [Imaginous/Cowboy_Untamed#27]
Why is this app closed source? I'd think the community has quite some competent developers that could support develop this app (and fix bugs).

**Comment by Imaginous** [comment]
The first reason is that I had to sign a Non Disclosure Agreement with the manufacturer of the motor controller. 
This information could partially be read in the source code.

I also don't want to make Cowboy any wiser on how we do things, to prevent them from blocking these features.

It's been a struggle for me since I started this project. Initially I made it just for myself, but made the choice of sharing it, with all risks involved.

That's why it's closed source.

**Comment by thrillfall** [comment]
Thanks for the answer.  And for your effort to provide this app!!
If you would split app frontend from the code that interacts with the motor controller the first could be open source.
