### ISSUE TITLE
Cowboy 3: write the value doesn't work anymore

### ISSUE THREAD

**Issue by DcFamas** [Imaginous/Cowboy_Untamed#5]
Hey there,
a few weeks ago I owned a Samsung Galaxy S10. On this phone I used v.2.x. of your App with my Cowboy 3.
My setting was Torque and field weakening to 15%. This worked like a charme.
Now I ordered a Samsung Galaxy S21 5G. I installed the newest version of the app and connected the original Cowboy App with my bike. Your app shows me, that the bike still got the setting 15% and no speed limit, but when I'd like to drive faster than 25km/h I can see in the original App, that the motor support suspends.

I already tried to reinstall the Untamed App, set the settings a few times and resetted the flash in the Expert Functions.

Do you know what to do? Best regards! :)

**Comment by Imaginous** [comment]
Which version of the original Cowboy app do you use? 

The fact that the app shows the correct settings it means that they are set in the bike. Did you get a firmware update for your bike?

Also I'd like the know if you have the same experience when you only unlock your bike with the Cowboy app and then start cycling (and use a GPS speedometer if you like to see the speed).

The only thing I can think of is that the original Cowboy software resets something.
I'm using the beta of the new Cowboy app and do not experience any changes on my V1+.

Changing the phone should not make any difference. Since the settings are stored in the bike.
The only other change I can think of is a newer version of the original app.

If you can supply me with the extra info we might figure out what's going on.

**Comment by Imaginous** [comment]
If you change to value to 10% for example, flash this... disconnect the bike, close the app. Restart the app and reconnect, does it still shows 10%?

**Comment by DcFamas** [comment]
Hey @Imaginous,
thanks for your extensive answer.

The original bike app is on v. 2.11.7 (5482) on Android 11. The bike version is 4.10.4.
I really don't know if there was an update of the bike. :/
There is no difference between the org. cowboy app and your app. The supportspeed still remains at 25km/h.

When I change the value to 10% and disconnect the bike, close the app and restart the app, the app shows again the 15% not the 10%. Same when I choose "Torque and speed limit". After the procedure the app shows again "Torque (no speed limit)" with 15%.

Should I try another phone? What would be the best method?

Best regards! :)

**Comment by Imaginous** [comment]
Your bike is still tweaked, so the phone should not matter.

It's strange that when you set it ton10% it's not stored. Did you press TEST, followed by FLASH?

If you didn't the value is not stored in the flash of the bike. Please make sure you use this procedure.

But the bike is still tweaked, so I don't understand why it should behave differently since you have a new phone. Since the phone doesn't do anything once the tweaks have been applied.

I'm using the beta of the original Cowboy app and even this one still works.

I think something else is going on, but have no clue what. Please check if the motor power cable is still connected properly and check the battery connectors on the bike and battery.

**Comment by DcFamas** [comment]
Hey there, my fault. I didd'nt prees TEST followed by FLASH. When I work this procedure out, the value will get changed. I changed from 10% to 20% back to 15%. But nevertheless the bike doesn't changed its behaviour. After 25km/h the throttle kicks in and I need to use my muscles. Is there anything else I can test? Maybe see some raw data or something?

Thank you and best regards! :)

**Comment by Imaginous** [comment]
It should not act differently since you swapped your phone.
Did you ever use "presets"?

The only thing I can think off is that you have flashed preset settings to your controller.

Or something is wrong with the bike.

**Comment by DcFamas** [comment]
I tried the presets when I got my new phone. Is there any way to flash the controller to DEFAULT and then start over again? Does the DEFAULT Button flash anything back?

**Comment by Imaginous** [comment]
I will look up the settings tomorrow, so you can restore the settings.
But if you did not use the FLASH button directly after using the presets, everything should be OK.

**Comment by Imaginous** [comment]
What you can do to reset the bike is set one of the presets to the following settings:

Field Weakening: Empty
Peddle Max Torque: Empty
Maximum Power 1-8: 100

Store this preset. Then unlock your bike by long pressing the presets icon and select the altered preset.
When your bike is unlocked and the preset is applied. Open Cowboy Untamed and connect to your bike. 
Then press the 'FLASH' button. This should restore the values as complete as possible.

Furthermore it seems your settings are still being stored in the bike. Therfore I close this bug report.
